### ISSUE TITLE
[bug] possible to add linebreaks to description

### ISSUE THREAD

**Issue by lhoffjann** [watercooler-labs/toggl-cli#71]
`toggl start` accepts linebreaks which have no affect on the UI but messes with e.g. `toggl list`

![Screenshot from 2023-12-19 10-10-36](https://github.com/watercooler-labs/toggl-cli/assets/5658862/94e7219d-0592-4912-a30a-03f9f49c8d63)
![Screenshot from 2023-12-19 10-10-02](https://github.com/watercooler-labs/toggl-cli/assets/5658862/d115b86c-fc69-413b-9ddc-6f84b37e6742)

**Comment by shantanuraj** [comment]
Hey, so yeah technically Toggl allows for newlines in time-entry descriptions at a storage level.
But of the official clients only the mobile app supported it. hmm I wonder if we can trim the description as a stop-gap.
A better fix would be to override display to indicate overflow with ellipsis.
