### ISSUE TITLE
don't start with panic

### ISSUE THREAD

**Issue by arcstur** [watercooler-labs/toggl-cli#74]
I just installed the tool (thank you a lot for making it!) and the first run already panicked. I think that gives a bad impression haha:

```
➜ toggl
thread 'main' panicked at src/credentials.rs:36:14:
failed to read from keyring: NoEntry
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Maybe running it without commands should show the help menu?

**Comment by shantanuraj** [comment]
Thanks for the report!

I think it's because the default option is to list running time entry and if 'auth' hasn't been competed it panics on trying to lookup the credentials.

I'll fix it in the next release.
