### ISSUE TITLE
Workspace Configuration Not Functioning as Expected

### ISSUE THREAD

**Issue by junseinagao** [watercooler-labs/toggl-cli#79]
Hi, I'm enjoying using this CLI tool for time tracking during development.

Recently, I started using Toggl with my team, so I need to manage both my personal and team workspaces. However, I noticed that the workspace configuration in the settings doesn't seem to be working as expected.

Here’s the configuration I'm trying to use:

```
# Branch (required)
 # Regex to choose which branch(-es) this block applies to, some examples
 # ['will/.*'] applies to branches like`will/release-workflows`
 # ['^\d+/.*'] applies to branches starting with numbers `123/feat-some-issue`
 # [main] applies only to the branch called `main`
 # ['*'] is the reserved default that applies if no block of higher precedence is present.
 # ['*'] It also applies if current folder is not tracked under source control
 ['*']

 # Workspace (optional, default=null)
 # in this context would resolve to the user's default workspace
 # https://support.toggl.com/en/articles/2452474-introduction-to-workspaces#switching-and-creating-workspaces
 workspace = "team workspace"

 # Description (optional, default="")
 # Accepts any string template with our macros in them
 description = "🔨 {{branch}}"

 # Project (optional, default=No project)
 # Accepts any string template with our macros in them
 project = "{{git_root}}"

 # Task (optional, default=No task)
 # task = "Some task"

 # Tags (optional, default=None)
 tags = ["code"]

 # Billable (optional, default=false)
 billable = true

 # This block will be applied to all branches that match the regex will/.*
 # Branches are matched top-down, so this block will be applied to all branches
 # that match the regex will/.* and no other block will be applied to them.
 # The exception is the default block, which is applied to all branches that
 # don't match any other block.

 # ['will/.*']
```

It appears that the workspace setting only pulls from the user's default workspace, regardless of the custom workspace defined in the config file.

[Reference code line](https://github.com/watercooler-labs/toggl-cli/blob/main/src/commands/start.rs#L106)

Do you have any plans to support custom workspace configurations in the future?

**Comment by shantanuraj** [comment]
Hey @junseinagao thanks for reporting this issue.
Yes currently configuration does not take workspace into account
https://github.com/watercooler-labs/toggl-cli/blob/fb1e8047fdd86d3227b783eca142841806f590d5/src/config/model.rs#L549-L557

I think it shouldn't be too difficult to support that now, I'll try and have a look into it.

**Comment by shantanuraj** [comment]
Hey @junseinagao I just saw this comment, I've created a pull-request that should make it work you.
If you could try it out, that'd be helpful!
