### ISSUE TITLE
Warning when outside of git directory

### ISSUE THREAD

**Issue by 0atman** [watercooler-labs/toggl-cli#84]
I think this warning should be suppressed, for use outside a git directory:

```diff
❯ toggl start  "description here"
-Failed to resolve token: Failed to resolve git root
Time entry started
$ [0:00:00]* –  description here
```

**Comment by 0atman** [comment]
Thank you so much!

**Comment by shantanuraj** [comment]
Hey you're right this code path should not evaluate unless the active config requires git.
I'll fix it asap.
Thanks!

**Comment by shantanuraj** [comment]
@0atman do you happen to have a config file as well?
I'm curious what your `toggl config` is.

I've created a patch to relax the dependency on `config` in the `start` command but that was another issue.
